### ISSUE TITLE
Speaker invalid: 500 internal server error

### ISSUE THREAD

**Issue by rakendu-droid** [Microsoft/Cognitive-SpeakerRecognition-Android#4]
I am trying to enroll for speaker recognition. I am unable to do it. I am getting a 500 internal error-invalid speaker response. I checked the audio file and It seems to be clear and the phrase is one from the list given. Is it possible that the server is not recognizing the phrase due to different accent? I have attached the audio file here. 
[phrase.wav.zip](https://github.com/Microsoft/Cognitive-SpeakerRecognition-Android/files/735292/phrase.wav.zip)

**Comment by mohgouda** [comment]
Thanks for reaching out.

I have tried to replicate your issue using the shared audio file, however I have received a different error code. I have received error code 400 "SpeechNotRecognized" and the reason is the accent spoken in the audio file was not recognised. Currently our Speaker Verification service support (en-US) locale, and the performance varies based on the accent provided.
Sorry about that, we are continuously working on improving our service to meet our customers' expectations.

Please don't hesitate to contact us in the case you have any further inquiries.

Regards,
Mohamed 
**Speaker Service PM**
